# Generated by Django 6.0.3 on 2026-03-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Producto')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Producto')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría (Ej: Cervezas, Licores)')),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Producto Activo?')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número de Mesa')),
                ('capacidad', models.IntegerField(default=4, verbose_name='Capacidad de personas')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Mesa Activa?')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sede', verbose_name='Sede a la que pertenece')),
            ],
        ),
    ]
