# Generated by Django 6.0.3 on 2026-03-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_producto_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto', verbose_name='Producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sede', verbose_name='Sede')),
            ],
            options={
                'unique_together': {('producto', 'sede')},
            },
        ),
    ]
