# Generated by Django 6.0.3 on 2026-03-15 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_pedido_detallepedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_cierre',
        ),
        migrations.AddField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_insumo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.pedido'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion.producto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cashier', 'Cajero'), ('waiter', 'Mesero')], default='waiter', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.sede'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sede'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.sede'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_cerradas', to='gestion.empleado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mesa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos_tomados', to='gestion.empleado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sede',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.IntegerField(default=1)),
                ('ingrediente', models.ForeignKey(limit_choices_to={'es_insumo': True}, on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('producto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='gestion.producto')),
            ],
        ),
    ]
