# Generated by Django 6.0.3 on 2026-04-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_pedido_fecha_cierre_inventario_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
