spring.application.name=copa-dorada-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/copadorada
spring.datasource.username=copadorada
spring.datasource.password=copadorada
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
