DROP TABLE IF EXISTS inventario CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS mesas CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS sedes CASCADE;

CREATE TABLE sedes (
  id BIGSERIAL PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE usuarios (
  id BIGSERIAL PRIMARY KEY,
  nombre VARCHAR(200) NOT NULL,
  email VARCHAR(200) NOT NULL UNIQUE,
  clave VARCHAR(200) NOT NULL,
  rol VARCHAR(80) NOT NULL,
  sede_id BIGINT NOT NULL REFERENCES sedes (id)
);

CREATE TABLE mesas (
  id BIGSERIAL PRIMARY KEY,
  sede_id BIGINT NOT NULL REFERENCES sedes (id),
  numero VARCHAR(20) NOT NULL,
  cupo INTEGER NOT NULL DEFAULT 4,
  ocupada BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE (sede_id, numero)
);

CREATE TABLE pedidos (
  id BIGSERIAL PRIMARY KEY,
  sede_id BIGINT NOT NULL REFERENCES sedes (id),
  mesa_id BIGINT REFERENCES mesas (id),
  cliente VARCHAR(200),
  items TEXT,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  estado VARCHAR(40) NOT NULL DEFAULT 'Abierto',
  metodo_pago VARCHAR(40)
);

CREATE TABLE inventario (
  id BIGSERIAL PRIMARY KEY,
  sede_id BIGINT NOT NULL REFERENCES sedes (id),
  producto VARCHAR(200) NOT NULL,
  cantidad INTEGER NOT NULL DEFAULT 0,
  unidad VARCHAR(40) NOT NULL DEFAULT 'unidad'
);
